'use strict';

const SEVERITY_ORDER = ['info', 'low', 'medium', 'high', 'critical'];
const BLOCK_SEVERITIES = ['high', 'critical'];
const MAX_PATTERN_LENGTH = 256;

function assertSeverity(severity) {
  if (SEVERITY_ORDER.indexOf(severity) === -1) {
    throw new RangeError('severity must be one of ' + SEVERITY_ORDER.join(', '));
  }
}

function assertControlShape(control) {
  if (!control || typeof control !== 'object') {
    throw new TypeError('each control must be an object');
  }
  if (typeof control.id !== 'string' || control.id.length === 0) {
    throw new TypeError('control missing id');
  }
  if (typeof control.label !== 'string' || control.label.length === 0) {
    throw new TypeError('control ' + control.id + ' missing label');
  }
  assertSeverity(control.severity);
  if (control.kind !== undefined && control.kind !== 'present' && control.kind !== 'absent') {
    throw new RangeError('control ' + control.id + ' kind must be present|absent');
  }
  if (typeof control.pattern !== 'string' || control.pattern.length === 0) {
    throw new TypeError('control ' + control.id + ' missing pattern');
  }
  if (control.pattern.length > MAX_PATTERN_LENGTH) {
    throw new RangeError('control ' + control.id + ' pattern exceeds ' + MAX_PATTERN_LENGTH + ' chars');
  }
  try {
    new RegExp(control.pattern, 'i');
  } catch (err) {
    throw new TypeError('control ' + control.id + ' has invalid pattern: ' + err.message);
  }
}

function normalizeConfig(config) {
  if (!config || typeof config !== 'object') {
    throw new TypeError('config must be an object');
  }
  if (!config.frameworks || typeof config.frameworks !== 'object') {
    throw new TypeError('config.frameworks is required');
  }
  const controls = [];
  for (const item of Object.entries(config.frameworks)) {
    const key = item[0];
    const framework = item[1];
    if (!framework || typeof framework !== 'object' || !Array.isArray(framework.controls)) {
      throw new TypeError('framework ' + key + ' must define a controls array');
    }
    const title = typeof framework.title === 'string' ? framework.title : key;
    for (const raw of framework.controls) {
      assertControlShape(raw);
      controls.push({
        framework: key,
        title,
        id: raw.id,
        label: raw.label,
        severity: raw.severity,
        kind: raw.kind || 'present',
        pattern: raw.pattern
      });
    }
  }
  return controls;
}

function evaluateControl(control, fileTexts) {
  const re = new RegExp(control.pattern, 'i');
  const evidence = [];
  for (const entry of fileTexts) {
    if (re.test(entry.text)) {
      evidence.push(entry.file);
    }
  }
  const present = evidence.length > 0;
  const passed = control.kind === 'absent' ? !present : present;
  return {
    framework: control.framework,
    title: control.title,
    id: control.id,
    label: control.label,
    severity: control.severity,
    kind: control.kind,
    pattern: control.pattern,
    passed: Boolean(passed),
    evidence
  };
}

function evaluateAll(controls, fileTexts) {
  if (!Array.isArray(controls) || !Array.isArray(fileTexts)) {
    throw new TypeError('controls and fileTexts must be arrays');
  }
  return controls.map((control) => evaluateControl(control, fileTexts));
}

function blockingGaps(results) {
  return results.filter((r) => !r.passed && BLOCK_SEVERITIES.indexOf(r.severity) !== -1);
}

function summarize(results) {
  const frameworks = [];
  for (const r of results) {
    let row = frameworks.find((candidate) => candidate.framework === r.framework);
    if (!row) {
      row = { framework: r.framework, passed: 0, total: 0 };
      frameworks.push(row);
    }
    row.total += 1;
    if (r.passed) {
      row.passed += 1;
    }
  }
  let passed = 0;
  for (const r of results) {
    if (r.passed) passed += 1;
  }
  return { frameworks, passed, total: results.length };
}

function statusText(result) {
  if (result.passed) return ':white_check_mark: PASS';
  if (BLOCK_SEVERITIES.indexOf(result.severity) !== -1) return ':red_circle: FAIL';
  return ':warning: WARN';
}

function evidenceText(result) {
  if (result.passed && result.kind === 'absent') return 'No matching data committed';
  if (result.passed && result.evidence.length > 0) {
    const shown = result.evidence.slice(0, 3);
    const suffix = result.evidence.length > 3 ? ' ...' : '';
    return shown.join(', ').replace(/\|/g, '\\|') + suffix;
  }
  return 'No evidence found';
}

function buildComplianceReport(results, meta) {
  const summary = summarize(results);
  const footer = meta && meta.scanned
    ? '\n**Scanned**: ' + meta.scanned + ' project files across ' +
      summary.frameworks.length + ' frameworks. Generated by scripts/compliance-check.js (R16).'
    : '';

  const frameworkRows = summary.frameworks.map((row) => {
    return '| ' + row.framework + ' | ' + row.passed + ' | ' + row.total + ' |';
  }).join('\n');

  const controlRows = results.map((r) => {
    return '| ' + r.id + ' | ' + r.label + ' | ' + r.severity + ' | ' + statusText(r) + ' | ' + evidenceText(r) + ' |';
  }).join('\n');

  const pie = '```mermaid\npie showData title "Compliance Controls by Status"\n    "Passed" : ' +
    summary.passed + '\n    "Failed" : ' + (summary.total - summary.passed) + '\n```';

  return '# Compliance Report - CMMI Level 4\n\n' +
    '## Framework Summary\n\n' +
    '| Framework | Passed | Total |\n' +
    '| :--- | :--- | :--- |\n' +
    frameworkRows + '\n\n' +
    '## Control Matrix\n\n' +
    '| ID | Control | Severity | Status | Evidence |\n' +
    '| :--- | :--- | :--- | :--- | :--- |\n' +
    controlRows + '\n\n' +
    '## Status Chart\n\n' +
    pie + '\n\n' +
    '## Status\n\n' +
    (blockingGaps(results).length > 0
      ? '**:red_circle: OUT OF COMPLIANCE - Merge BLOCKED (R10)**\n\n' +
        blockingGaps(results).map((r) => '- ' + r.id + ' (' + r.framework + ', ' + r.severity + '): ' + r.label).join('\n')
      : ':white_check_mark: All high/critical controls satisfied.') +
    footer + '\n';
}

module.exports = {
  SEVERITY_ORDER,
  BLOCK_SEVERITIES,
  normalizeConfig,
  evaluateControl,
  evaluateAll,
  blockingGaps,
  summarize,
  buildComplianceReport
};