from json import dumps
from re import findall
from sys import argv
from datetime import datetime

with open(argv[1], 'r') as f:
    lines = [
        line.strip('\n')
            for line in f.readlines()
        if(
            'class ' in line or
            'def ' in line
        )
    ]

structural_map = []
indent_list = set()
for line in lines:
    current_indent = len(findall('([ ]*)[^ ]*', line)[0])
    indent_list.add(current_indent)
    if('class ' in line):
        current_class = findall('class ([^)(:]+)', line)[0]
        structural_map += [('class', current_indent, current_class)]
    else:
        current_def = findall('def ([^(]+)', line)[0]
        structural_map += [('def', current_indent, current_def)]

indent_list = list(indent_list)
indent_perunit = int(sum(indent_list) / sum([i for i in range(len(indent_list))]))
indent_space_perunit = ''.join([' ' for i in range(indent_perunit)])

xml = ''
last_indent_space = ''
data0 = structural_map[0]

if len(argv) > 2 and argv[2].upper() == "README":
    for data in structural_map:
        prefix = f">>> ::{data[2]}" if data[0] == 'class' else f">>> {data[2]}()"
        print(f"{''.join([' ' for i in range(data[1])])}{prefix}")

for data in structural_map[1:]:
    data1 = data
    if(data1[1] > data0[1]):
        last_indent_space += indent_space_perunit
        xml += f'\n{last_indent_space}'
        if(data1[0] in ['class']):
            xml += f'<div className="{data1[2]}">'
        else:
            xml += f'<div methodName="{data1[2]}">'
    else:
        if(data1[1] < data0[1]):
            last_indent_space = last_indent_space[:-len(indent_space_perunit)]
            if(
                (data0[0] == 'def' and data1[0] == 'class') or
                (data0[0] == 'def' and data1[0] == 'def')
            ):
                xml += '</div>'
            xml += f'\n{last_indent_space}'
            if(
                (data0[0] == 'def' and data1[0] == 'class') or
                (data0[0] == 'def' and data1[0] == 'def')
            ):
                xml += '</div>'
            xml += f'\n{last_indent_space}'
            if(data1[0] in ['class']):
                xml += f'<div className="{data1[2]}">'
            else:
                xml += f'<div methodName="{data1[2]}">'
        else:
            if(data0[0] == 'def' and data1[0] == 'def'):
                xml += '</div>'
            xml += f'\n{last_indent_space}'
            if(data1[0] in ['class']):
                xml += f'<div className="{data1[2]}">'
            else:
                xml += f'<div methodName="{data1[2]}">'

    data0 = data

print('\n'.join([
    '[Structure] *',
    f'<!-- Generated by "{argv[0]}" on "{datetime.isoformat(datetime.now())}" -->',
    f'{indent_space_perunit}<div className="{structural_map[0][2]}">{xml}\n{indent_space_perunit}</div>\n{indent_space_perunit}</div>'
]).replace(
    '\n',
    f'\n{indent_space_perunit}'
))
